log_level = "warn"
outputs = { Targets = ["eDP-2"] }
position = "Top"
enable_esc_key = true
app_launcher_cmd = "vincienae"

[modules]
left = [ [ "appLauncher",  "Tray" ] ]
center = [ "Clock" , "Workspaces" ]
right = [ ["MediaPlayer", "Privacy", "Settings" ] , ["Updates" , "Notifications"] ]

[updates]
check_cmd = "checkupdates; paru -Qua"
update_cmd = 'ghostty -e bash -c "paru; echo Done - Press enter to exit; read" &'

[workspaces]
enable_workspace_filling = true
visibility_mode = "MonitorSpecific"

[[CustomModule]]
name = "appLauncher"
icon = "󱗼"
command = "vicinae toggle"

[[CustomModule]]
name = "Notifications"
icon = ""
command = "swaync-client -t -sw"
listen_cmd = "swaync-client -swb"
icons.'dnd.*' = ""
alert = ".*notification"

[window_title]
truncate_title_after_length = 120

[clock]
format = "%r"

[system_info]
indicators = [ "Memory", "Temperature" ]

[settings]
lock_cmd = "playerctl --all-players pause; nixGL hyprlock &"
audio_sinks_more_cmd = "pavucontrol -t 3"
audio_sources_more_cmd = "pavucontrol -t 4"
wifi_more_cmd = "nm-connection-editor"
vpn_more_cmd = "nm-connection-editor"
bluetooth_more_cmd = "blueman-manager"

[[settings.CustomButton]]
name = "File Manager"
icon = "A"
command = "yazi"
tooltip = "Open File Manager"

[appearance]
style = "Islands"
font_name = "JetBrainsMono Nerd Font Mono"
scale_factor = 1.3
opacity = 0.95

primary_color = "#7aa2f7"
success_color = "#9ece6a"
text_color = "#a9b1d6"

workspace_colors = [ "#7aa2f7", "#9ece6a" ]

[appearance.danger_color]
base = "#f7768e"
weak = "#e0af68"

[appearance.background_color]
base = "#1a1b26"
weak = "#24273a"
strong = "#414868"

[appearance.secondary_color]
base = "#0c0d14"
